global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['web:8014']
    metrics_path: '/metrics'

  - job_name: 'video_pipeline'
    static_configs:
      - targets: ['video_pipeline:8014']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 