global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:
  - job_name: 'flask_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['web:8014']
    metrics_path: '/metrics'

  - job_name: 'video_pipeline'
    scrape_interval: 5s
    static_configs:
      - targets: ['video_pipeline:8000']
    metrics_path: '/metrics'

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090'] 